version: "3.8"

services:
  koinonia:
    image: "koinonia"
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./certs:/etc/certs
    environment:
      CERT_FILE: ${CERT_FILE}
      KEY_FILE: ${KEY_FILE}
