version: "3.8"

services:
  koinonia:
    image: "koinonia"
    build: .
    restart: always

  coturn:
    image: coturn/coturn
    ports:
      - 3478:3478/udp
      # max port is low because docker has serious performance issues with many ports
      - 49152-49160:49152-49160/udp
    command: "-n --max-port=49160 -a -r koinonia -f -u koinonia:koinonia -X $$(detect-external-ip)"

  nginx_proxy:
    image: "koinonia-proxy"
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - koinonia
      - coturn
