version: "3.8"

services:
  koinonia:
    image: "koinonia"
    build: .
    restart: always

  nginx_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/etc/static
    ports:
      - 8080:80
    depends_on:
      - koinonia
