version: "3.8"

services:
  koinonia:
    image: "koinonia"
    build: .
    restart: always

  coturn:
    image: coturn/coturn
    # TODO: change to ports
    network_mode: host
    # TODO: maybe make password rotate every n minutes so this can't be easily exploited
    command: "-n -a -r koinonia -v -f -u koinonia:koinonia -X $$(detect-external-ip)"

  nginx_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/etc/static
    ports:
      - 8080:80
    depends_on:
      - koinonia
      - coturn
