name: "build"

on: ["push", "pull_request"]

jobs:
  build-nix:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"

    - uses: "cachix/install-nix-action@v17"
      with:
        nix_path: "nixpkgs=channel:nixos-22.05"

    - name: "build"
      run: "nix-build"

  build-windows:
    runs-on: "windows-latest"

    steps:
    - uses: "actions/checkout@v2"

    - name: "dependencies"
      run: "vcpkg install drogon:x64-windows && vcpkg integrate install && mkdir build"

    - name: "build"
      run: "cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake && cmake --build . --parallel && mv static Debug"
      working-directory: "build"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "windows"
        path: "build/Debug"
