name: "build"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "alpine:latest"

    strategy:
      matrix:
        include:
          - build: "Plugins Enabled"
            use_plugins: "on"
          - build: "Plugins Disabled"
            use_plugins: "off"

    steps:
    - name: "dependancies"
      run: "apk add --no-cache gcc g++ cmake ninja jsoncpp-dev zlib-dev util-linux-dev git"

    - name: "install lua"
      if: matrix.use_plugins == 'ON'
      run: "apk add --no-cache lua-dev"

    - uses: "actions/checkout@v2"

    - name: "configure cmake"
      run: "mkdir build && cd build && cmake --configure .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DUSE_LUA_PLUGINS=${{matrix.use_plugins}}"

    - name: "build project"
      run: "cmake --build . -j $(nproc)"
      working-directory: "build"

    - name: "make release directory"
      run: "mkdir release && cp build/koinonia release && cp build/static release -r"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "server (plugins ${{matrix.use_plugins}})"
        path: "release"
