name: "build"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"

    - name: "build project"
      run: "docker build -t koinonia ."

    - name: "export image"
      run: "docker save koinonia > koinonia.tar"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "docker image"
        path: "koinonia.tar"
