name: "build"

on:
  push:
    branches: ["main"]

jobs:
  build-docker:
    runs-on: "ubuntu-latest"

    env:
      ECR_REPO: "public.ecr.aws/x9a4j9i2"

    steps:
    - name: "login to ECR"
      uses: "docker/login-action@v1"
      with:
        registry: "public.ecr.aws"
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - uses: "actions/checkout@v2"

    - name: "build"
      run: "docker build -t koinonia ."

    - name: "export"
      run: "docker save koinonia > koinonia.tar"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "docker image"
        path: "koinonia.tar"

    - name: "push to ECR"
      run: "docker tag koinonia $ECR_REPO/koinonia:latest && docker push $ECR_REPO/koinonia:latest"
